// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrainingApp.Data;

#nullable disable

namespace TrainingApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230731162529_DurationChange")]
    partial class DurationChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrainingApp.Features.Authentication.Models.UserSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("TrainingApp.Features.Trainings.Fixed_drills.FixedDrill", b =>
                {
                    b.Property<int>("FixedDrillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FixedDrillId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("FixedDrillId");

                    b.ToTable("FixedDrills");
                });

            modelBuilder.Entity("TrainingApp.Features.Trainings.UserTraining", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrainingId"));

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("AgeGroup");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("Date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TrainingId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTraining");
                });

            modelBuilder.Entity("TrainingApp.Features.Trainings.UserTrainingDrills.UserTrainingDrill", b =>
                {
                    b.Property<int>("UserTrainingDrillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserTrainingDrillId"));

                    b.Property<int>("DrillId")
                        .HasColumnType("integer");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<int>("UserTrainingId")
                        .HasColumnType("integer");

                    b.HasKey("UserTrainingDrillId");

                    b.HasIndex("DrillId");

                    b.HasIndex("UserTrainingId");

                    b.ToTable("UserTrainingDrills");
                });

            modelBuilder.Entity("TrainingApp.Features.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TrainingApp.Features.Authentication.Models.UserSession", b =>
                {
                    b.HasOne("TrainingApp.Features.Users.User", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingApp.Features.Trainings.UserTraining", b =>
                {
                    b.HasOne("TrainingApp.Features.Users.User", "User")
                        .WithMany("UserTrainings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingApp.Features.Trainings.UserTrainingDrills.UserTrainingDrill", b =>
                {
                    b.HasOne("TrainingApp.Features.Trainings.Fixed_drills.FixedDrill", "FixedDrill")
                        .WithMany("UserTrainingDrills")
                        .HasForeignKey("DrillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingApp.Features.Trainings.UserTraining", "UserTraining")
                        .WithMany("UserTrainingDrills")
                        .HasForeignKey("UserTrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FixedDrill");

                    b.Navigation("UserTraining");
                });

            modelBuilder.Entity("TrainingApp.Features.Trainings.Fixed_drills.FixedDrill", b =>
                {
                    b.Navigation("UserTrainingDrills");
                });

            modelBuilder.Entity("TrainingApp.Features.Trainings.UserTraining", b =>
                {
                    b.Navigation("UserTrainingDrills");
                });

            modelBuilder.Entity("TrainingApp.Features.Users.User", b =>
                {
                    b.Navigation("UserSessions");

                    b.Navigation("UserTrainings");
                });
#pragma warning restore 612, 618
        }
    }
}
